import * as vscode from 'vscode';
import { ApiRoute } from '../models/route';
import { RouteAnalysisResult } from '../analysis/routeAnalyzer';
import { getRouteKey } from '../analysis/routeRelationshipAnalyzer';

/**
 * Structured route data object for JSON export.
 */
export interface ExportedRouteItem {
  method: string;
  path: string;
  framework: string;
  filePath: string;
  line: number;
  column: number;
  health?: string;
  issues?: string[];
  middleware?: Array<{ name: string; type: string }>;
  isDuplicate?: boolean;
  isShared?: boolean;
  hasConflicts?: boolean;
  isShadowed?: boolean;
}

/**
 * Generates a deterministic, formatted JSON array string of discovered and analyzed routes.
 */
export function exportRoutesToJson(
  routes: ApiRoute[],
  analysis?: RouteAnalysisResult
): string {
  const duplicateKeys = new Set<string>();
  const sharedKeys = new Set<string>();

  if (analysis) {
    for (const group of analysis.duplicates) {
      for (const r of group.routes) {
        duplicateKeys.add(getRouteKey(r));
      }
    }
    for (const group of analysis.sharedPaths) {
      for (const r of group.routes) {
        sharedKeys.add(getRouteKey(r));
      }
    }
  }

  const items: ExportedRouteItem[] = routes.map((r) => {
    const key = getRouteKey(r);
    const rel = analysis?.relationships?.get(key);

    const hasConflict = !!rel?.conflicts && rel.conflicts.length > 0;
    const isShadow = hasConflict && rel!.conflicts.some((c) => c.isShadowing);

    return {
      method: r.method,
      path: r.path,
      framework: r.framework || 'express',
      filePath: r.filePath,
      line: r.line + 1,
      column: r.column + 1,
      health: rel?.health || 'healthy',
      issues: rel?.issues?.map((i) => i.message),
      middleware: rel?.middleware?.map((m) => ({ name: m.name, type: m.type })),
      isDuplicate: duplicateKeys.has(key),
      isShared: sharedKeys.has(key),
      hasConflicts: hasConflict,
      isShadowed: isShadow,
    };
  });

  return JSON.stringify(items, null, 2);
}

/**
 * Generates a developer-readable Markdown document documenting all routes.
 */
export function exportRoutesToMarkdown(
  routes: ApiRoute[],
  analysis?: RouteAnalysisResult
): string {
  const lines: string[] = [];

  lines.push('# API Routes Inventory\n');
  lines.push(`Generated by **API Route Explorer** on ${new Date().toLocaleDateString()}.\n`);
  lines.push(`- **Total Routes**: ${routes.length}`);
  if (analysis) {
    lines.push(`- **Total Files**: ${analysis.statistics.totalFiles}`);
    lines.push(`- **Healthy Routes**: ${analysis.statistics.healthyCount}`);
    lines.push(`- **Warnings**: ${analysis.statistics.warningCount}`);
    lines.push(`- **Errors**: ${analysis.statistics.errorCount}`);
  }
  lines.push('\n---\n');

  // Group by framework in canonical order
  const fwMap = new Map<string, ApiRoute[]>();
  for (const r of routes) {
    const fw = r.framework || 'express';
    let list = fwMap.get(fw);
    if (!list) {
      list = [];
      fwMap.set(fw, list);
    }
    list.push(r);
  }

  const canonicalFrameworks = ['express', 'nextjs', 'fastify', 'nestjs'];
  const allFrameworks = Array.from(fwMap.keys()).sort((a, b) => {
    const idxA = canonicalFrameworks.indexOf(a);
    const idxB = canonicalFrameworks.indexOf(b);
    if (idxA !== -1 && idxB !== -1) {
      return idxA - idxB;
    }
    if (idxA !== -1) {
      return -1;
    }
    if (idxB !== -1) {
      return 1;
    }
    return a.localeCompare(b);
  });

  for (const framework of allFrameworks) {
    const fwRoutes = fwMap.get(framework) || [];
    let fwTitle = 'Express';
    if (framework === 'nextjs' || framework === 'next') {
      fwTitle = 'Next.js';
    } else if (framework === 'fastify') {
      fwTitle = 'Fastify';
    } else if (framework === 'nestjs') {
      fwTitle = 'NestJS';
    } else {
      fwTitle = framework.charAt(0).toUpperCase() + framework.slice(1);
    }

    lines.push(`## ${fwTitle} (${fwRoutes.length} routes)\n`);

    // Sort by path, then method
    const sorted = [...fwRoutes].sort((a, b) => {
      const cmp = a.path.localeCompare(b.path);
      return cmp !== 0 ? cmp : a.method.localeCompare(b.method);
    });

    for (const r of sorted) {
      const rel = analysis?.relationships?.get(getRouteKey(r));
      const isWarning = rel?.health === 'warning';
      const isError = rel?.health === 'error';
      const healthBadge = isError ? '❌ Error' : isWarning ? '⚠️ Warning' : '🟢 Healthy';
      const headingPrefix = isError ? '❌ ' : isWarning ? '⚠️ ' : '';

      lines.push(`### ${headingPrefix}\`${r.method}\` ${r.path}`);
      lines.push(`- **Source**: \`${r.filePath}:${r.line + 1}\``);
      lines.push(`- **Health**: ${healthBadge}`);

      if (rel?.issues && rel.issues.length > 0) {
        lines.push(`- **Issues**:`);
        for (const issue of rel.issues) {
          lines.push(`  - ${issue.message}`);
        }
      }

      if (rel?.middleware && rel.middleware.length > 0) {
        const mwNames = rel.middleware.map((m) => `\`${m.name}\` (${m.type})`).join(', ');
        lines.push(`- **Middleware**: ${mwNames}`);
      }

      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Prompts user to select format and destination, exporting the route inventory safely.
 */
export async function showExportRoutesDialog(
  routes: ApiRoute[],
  analysis?: RouteAnalysisResult
): Promise<void> {
  if (routes.length === 0) {
    vscode.window.showInformationMessage('No API routes available to export.');
    return;
  }

  interface FormatPickItem extends vscode.QuickPickItem {
    format: 'json' | 'markdown';
  }

  const pick = await vscode.window.showQuickPick<FormatPickItem>(
    [
      {
        label: '$(json) Export as JSON',
        description: 'Structured, machine-readable format (.json)',
        format: 'json',
      },
      {
        label: '$(markdown) Export as Markdown',
        description: 'Formatted documentation with health and middleware details (.md)',
        format: 'markdown',
      },
    ],
    {
      title: 'API Route Explorer: Export Routes',
      placeHolder: 'Select export format',
    }
  );

  if (!pick) {
    return;
  }

  const defaultFileName = pick.format === 'json' ? 'api-routes.json' : 'api-routes.md';
  const filterLabel = pick.format === 'json' ? 'JSON' : 'Markdown';
  const fileExt = pick.format === 'json' ? ['json'] : ['md'];

  const defaultUri = vscode.workspace.workspaceFolders?.[0]
    ? vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, defaultFileName)
    : undefined;

  const saveUri = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { [filterLabel]: fileExt },
    title: `Save API Routes as ${filterLabel}`,
  });

  if (!saveUri) {
    return;
  }

  const content =
    pick.format === 'json'
      ? exportRoutesToJson(routes, analysis)
      : exportRoutesToMarkdown(routes, analysis);

  const encoder = new TextEncoder();
  await vscode.workspace.fs.writeFile(saveUri, encoder.encode(content));

  const action = await vscode.window.showInformationMessage(
    `Exported ${routes.length} routes to ${saveUri.fsPath.split('/').pop()}`,
    'Open File'
  );

  if (action === 'Open File') {
    const doc = await vscode.workspace.openTextDocument(saveUri);
    await vscode.window.showTextDocument(doc);
  }
}
