import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/lib/site-config";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { CodeBlock } from "@/components/CodeBlock";

export const metadata: Metadata = {
  title: "OpenAPI 3.0.3 Generation — Export JSON & YAML",
  description:
    "Learn how to generate and export valid OpenAPI 3.0.3 specifications directly from your workspace routes in API Routes Explorer.",
  alternates: {
    canonical: `${siteConfig.url}/docs/openapi`,
  },
  openGraph: {
    title: "OpenAPI 3.0.3 Generation — API Routes Explorer Docs",
    description: "Export OpenAPI 3.0.3 specifications in JSON and YAML formats without runtime servers.",
    url: `${siteConfig.url}/docs/openapi`,
  },
};

export default function OpenApiDocsPage() {
  return (
    <div className="space-y-10">
      <Breadcrumbs
        items={[
          { name: "Docs", href: "/docs" },
          { name: "OpenAPI Generation", href: "/docs/openapi" },
        ]}
      />

      <div className="space-y-4">
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-[var(--foreground)]">
          OpenAPI 3.0.3 Generation &amp; Export
        </h1>
        <p className="text-base text-[var(--muted)] leading-relaxed">
          Transform discovered backend endpoints into standardized OpenAPI 3.0.3 specifications. Export complete API schemas in JSON or YAML format without configuring complex build pipelines.
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-[var(--foreground)]">Why OpenAPI from Code?</h2>
        <p className="text-xs sm:text-sm text-[var(--muted)] leading-relaxed">
          Keeping documentation in sync with fast-moving codebases is traditionally prone to human error and drift. API Routes Explorer inspects your actual code definitions and extracts:
        </p>
        <ul className="space-y-1.5 text-xs sm:text-sm text-[var(--foreground)]">
          <li>• <strong>Accurate Path Templates:</strong> Translates dynamic segments (such as <code>:id</code> or <code>[id]</code>) to OpenAPI compliant curly braces <code>&#123;id&#125;</code>.</li>
          <li>• <strong>HTTP Verbs:</strong> Maps verbs (GET, POST, PUT, DELETE, PATCH) into valid operation objects.</li>
          <li>• <strong>Path Parameters:</strong> Automatically derives required parameter definitions with string types for detected dynamic tokens.</li>
          <li>• <strong>Operation Tags:</strong> Groups endpoints into OpenAPI tags using detected controller names or resource segments.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-[var(--foreground)]">Exporting OpenAPI (JSON / YAML)</h2>
        <p className="text-xs sm:text-sm text-[var(--muted)] leading-relaxed">
          Open the Command Palette (<kbd className="px-1.5 py-0.5 rounded bg-[var(--surface-elevated)] border border-[var(--surface-border)] text-xs">Cmd+Shift+P</kbd>) and run:
        </p>
        <ul className="space-y-1 text-xs font-mono text-emerald-400">
          <li>• <code>API Routes Explorer: Export OpenAPI as JSON</code></li>
          <li>• <code>API Routes Explorer: Export OpenAPI as YAML</code></li>
        </ul>
        <p className="text-xs sm:text-sm text-[var(--muted)] leading-relaxed">
          The extension compiles your routes and lets you choose whether to open the generated spec in a new editor tab or write it directly to <code>openapi.json</code> or <code>openapi.yaml</code>.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-[var(--foreground)]">Specification Example</h2>
        <CodeBlock
          language="yaml"
          title="Generated openapi.yaml"
          badge="OpenAPI 3.0.3"
          code={`openapi: 3.0.3
info:
  title: Workspace API
  version: 1.0.0
  description: Generated by API Routes Explorer for VS Code
paths:
  /api/v1/users/{id}:
    get:
      summary: Get user by ID
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found`}
        />
      </section>

      {/* Navigation Footer */}
      <div className="pt-6 border-t border-[var(--surface-border)] flex items-center justify-between text-xs">
        <Link href="/docs/http-client" className="text-[var(--muted)] hover:text-[var(--foreground)]">
          ← Native HTTP Client
        </Link>
        <Link href="/docs/troubleshooting" className="text-emerald-400 font-semibold hover:underline">
          Troubleshooting Guide →
        </Link>
      </div>
    </div>
  );
}
